config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :events

  namespace :admin do
    root "events#index"
    resources :events
    resources :categories
  end

  root "events#index"
  
  get "/faq" => "pages#faq"
  
  resource :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  STATUS = ["draft", "public", "private"]
  
  validates_presence_of :name, :friendly_id  
  validates_uniqueness_of :friendly_id
  validates_format_of :friendly_id, :with => /\A[a-z0-9\-]+\z/
  validates_inclusion_of :status, :in => STATUS
  
  belongs_to :category, :optional => true
  
  def to_param
    self.friendly_id
  end
  
  protected

  def generate_friendly_id
    self.friendly_id ||= SecureRandom.uuid
  end  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def display_name
    self.email.split("@").first
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to admin_categories_path
    else
      render "new"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to admin_categories_path
    else
      render "edit"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to admin_categories_path
  end

  protected
  def category_params
    params.require(:category).permit(:name)
  end  
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find_by_friendly_id!(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to admin_events_path
    else
      render "new"
    end
  end

  def edit
    @event = Event.find_by_friendly_id!(params[:id])
  end

  def update
    @event = Event.find_by_friendly_id!(params[:id])

    if @event.update(event_params)
      redirect_to admin_events_path
    else
      render "edit"
    end
  end

  def destroy
    @event = Event.find_by_friendly_id!(params[:id])
    @event.destroy

    redirect_to admin_events_path
  end

  protected
  def event_params
    params.require(:event).permit(:name, :description, :friendly_id, :status, :category_id)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  layout "admin"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale
  before_action :set_timezone
  
  def set_locale
    if params[:locale] && I18n.available_locales.include?( params[:locale].to_sym )
      session[:locale] = params[:locale]
    end

    I18n.locale = session[:locale] || I18n.default_locale  
  end
  
  def set_timezone
    if current_user && current_user.time_zone
      Time.zone = current_user.time_zone
    end
  end  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find_by_friendly_id!(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(user_params)
      flash[:notice] = "修改成功"
      redirect_to edit_user_path
    else
      render "edit"
    end
  end

  protected
  def user_params
    params.require(:user).permit(:time_zone)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  # def display_event_status(event)
  #   case event.status
  #     when "draft"
  #       "草稿"
  #     else
  #       ""
  #   end
  # end  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/events/_form.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@event.errors.count, "error") %> prohibited this person from being saved:</h2>

    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :friendly_id %>
  <%= f.text_field :friendly_id, :required => true, :class => "form-control" %>
  <p class="help-block">限小写英数字及横线，将作为网址的一部分</p>
</div>

<div class="form-group">
  <%= f.label :category_id %>
  <%= f.select :category_id, Category.all.map{ |c| [c.name, c.id] }, {}, :class => "form-control" %>
</div>

<div class="btn-group" data-toggle="buttons">
  <%= f.label :status %>
  </br>
  <% Event::STATUS.each do |status| %>
    <label class="btn btn-default <%= (status == f.object.status)? 'active' : '' %>">
      <%= f.radio_button :status, status %>
      <%= t(status, :scope => "event.status") %>
    </label>
  <% end %>
</div>

<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, :class => "form-control" %>
</div>

<script>
  $("#event_category_id").select2( { theme: "bootstrap"} );
</script>

app/views/admin/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_for [:admin, @event] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "Update", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_events_path %>
  </div>
<% end %>

app/views/admin/events/index.html.erb
<h1><%= t("admin.event_list") %></h1>

<p class="text-right">
<%= link_to "New Event", new_admin_event_path, :class => "btn btn-primary" %>
</p>

<table class="table">
<tr>
  <th>Event Name</th>
  <th>Actions</th>
</tr>
<% @events.each do |event| %>
  <tr>
    <td><%= link_to event.name, admin_event_path(event) %></td>
    <td>
      <%= link_to "Edit", edit_admin_event_path(event), :class => "btn btn-default" %>
      <%= link_to "Delete", admin_event_path(event), :method => "delete", :data => { :confirm => "Are you sure?" }, :class => "btn btn-danger" %>
  </tr>
<% end %>
</table>

app/views/admin/events/new.html.erb
<h1>New Event</h1>

<%= form_for [:admin, @event] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "Create", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_events_path %>
  </div>
<% end %>

app/views/admin/events/show.html.erb
<h1><%= @event.name %></h1>
<h2><%= @event.category.try(:name) %></h2>

<p>
  <%= link_to "打开前台", event_path(@event), :target => "_blank", :class => "btn btn-primary" %>
</p>

<%= simple_format @event.description %>

app/views/events/index.html.erb
<h1><%= t("event_list") %></h1>

<ul>
  <% @events.each do |event| %>
    <li>
      <%= link_to event.name, event_path(event) %> 
      <!-- <%= event.created_at.to_s %> # default format--> 
      <%= event.created_at.to_s(:ymd) %>
    </li>
  <% end %>
</ul>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<h2><%= t(@event.status, :scope => "event.status") %></h2>
<h2><%= @event.category.try(:name) %></h2>

<%= simple_format @event.description %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/admin/">Recipes 后台</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <li class="active"><%= link_to('活动管理', admin_events_path) %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user"></span> <%= current_user.display_name %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "回到前台", root_path %></li>
                  <li><%= link_to('修改密码', edit_registration_path(:user)) %></li>
                  <li><%= link_to('退出', destroy_user_session_path, :method => :delete) %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to('注册', new_registration_path(:user)) %></li>
              <li><%= link_to('登录', new_session_path(:user)) %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>


      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">


      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Recipes 前台</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to "活动一览", events_path %></li>
            </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user"></span> <%= t( "hello", :name => current_user.display_name) %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to('管理员面板', admin_events_path) %></li>
                  <li><%= link_to('修改个人资料', edit_user_path) %></li>
                  <li><%= link_to('修改密码', edit_registration_path(:user)) %></li>
                  <li><%= link_to('退出', destroy_user_session_path, :method => :delete) %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to('注册', new_registration_path(:user)) %></li>
              <li><%= link_to('登录', new_session_path(:user)) %></li>
            <% end %>
          </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>


      <%= yield %>
      <%= link_to "FAQ", faq_path %>
      <%= link_to "中文版", :controller => controller_name, :action => action_name, :locale => "zh-CN" %>
      <%= link_to "English", :controller => controller_name, :action => action_name, :locale => "en" %>      
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<h2>Edit User</h2>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :time_zone %>
    <%= f.time_zone_select :time_zone %>
  </div>

  <div class="form-group">
    <%= f.submit "Save", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>